# forward

In [49]:
from torch import nn
import torch
from torch.utils.tensorboard import SummaryWriter


class MyNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.relu1 = nn.ReLU()

    def forward(self, x):
        return self.relu1(x)

In [50]:
net = MyNet()
x = torch.tensor(1.0)
y = net(x) # forward
print(y)

tensor(1.)


# Reshape

In [1]:
import torch
input = torch.tensor([
    [1 , -0.5],
    [-1 , 3],
    [3, 0.5]
])
print(input)

tensor([[ 1.0000, -0.5000],
        [-1.0000,  3.0000],
        [ 3.0000,  0.5000]])


### (-1,) 和 (1,-1)的区别

In [40]:
input_reshape_vector = input.reshape(-1,)
print(input_reshape_vector)

tensor([ 1.0000, -0.5000, -1.0000,  3.0000,  3.0000,  0.5000])


In [41]:
input_reshape_matrix = input.reshape(1,-1)
print(input_reshape_matrix)

tensor([[ 1.0000, -0.5000, -1.0000,  3.0000,  3.0000,  0.5000]])


# 展平的所有操作

In [49]:
import torch
input = torch.randn(64,3,32,32)
print(input.shape)

torch.Size([64, 3, 32, 32])


展成向量

In [50]:
output_flt_1 = input.reshape(-1,)
print(output_flt_1.shape)

torch.Size([196608])


In [51]:
output_flt_2 = torch.flatten(input, 0)
print(output_flt_2.shape)

torch.Size([196608])


展成batch_size个向量

In [52]:
output_flt_3 = input.reshape(input.size(dim=0), -1)
print(output_flt_3.shape)

torch.Size([64, 3072])


In [53]:
output_flt_4 = torch.flatten(input,start_dim=1)
print(output_flt_3.shape)

torch.Size([64, 3072])


In [54]:
output_flt_5 = nn.Flatten()(input) # 默认从第一维开始展平
print(output_flt_3.shape)

torch.Size([64, 3072])


# ReLU

In [ ]:
from torch import nn
import torch
from torch.nn import ReLU

class MyNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2, 2)
        self.relu1 = nn.ReLU()
        self.bn1 = nn.BatchNorm1d(num_features=1)
        self.relu2 = nn.ReLU()
        self.bn2 = nn.BatchNorm1d(num_features=1)
        self.encoder = nn.Sequential(
            self.relu1,
            self.bn1,
            self.relu2,
            self.bn2
        )

    def forward(self, x):
        return self.relu1(x)

In [52]:
output = net(input)
print(output)


tensor([[1.0000, 0.0000],
        [0.0000, 3.0000],
        [3.0000, 0.5000]])


# Model

In [11]:
import torch
from torch import nn

In [63]:
class MyCNNModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.CNN = nn.Sequential(
            nn.Conv2d(3,32,5,padding=2),
            nn.MaxPool2d(2),
            nn.Conv2d(32,32,5,padding=2),
            nn.MaxPool2d(2),
            nn.Conv2d(32,64,5,padding=2),
            nn.MaxPool2d(2)
        )
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(1024,64)
        self.fc2 = nn.Linear(64,2)
    def forward(self, x):
        x = self.CNN(x)
        x = self.flatten(x)
        x = self.fc1(x)
        x = self.fc2(x)
        return x

In [64]:
batch_data = torch.randn(64,3,32,32)
model = MyCNNModel()
output = model(batch_data)
print(output.shape)
print(model)

torch.Size([64, 2])
MyCNNModel(
  (CNN): Sequential(
    (0): Conv2d(3, 32, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (2): Conv2d(32, 32, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(32, 64, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (fc1): Linear(in_features=1024, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=2, bias=True)
)


In [66]:
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter("../experiments/logs/myCNNmodel")
writer.add_graph(model, batch_data)
writer.close()